server:
  port: 8761
spring:
  application:
    name: Discovery-Server

eureka:
  instance:
    appname: ${spring.application.name}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF