spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hello
        uri: lb://hello/
        predicates:
        - Path=/hello
      - id: world
        uri: lb://world/
        predicates:
        - Path=/world